// === Parameters template ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class {{parametersClassName}} {
    {% for p in parameters -%}
    /**
    * Label: {{p.label}}, type: {{p.type}}
    */
    {{p.varType}} {{p.varName}}
    {% endfor %}

    static {{parametersClassName}} initParameters(StepParameters sp) {
        {{parametersClassName}} parameters = new {{parametersClassName}}()

        {% for p in parameters -%}
        {% if p.type == 'checkbox' %}def {{p.varName}} = sp.getParameter('{{p.name}}').value == "true"{% else %}def {{p.varName}} = sp.{{p.methodName}}('{{p.name}}').value{% endif %}
        parameters.{{p.varName}} = {{p.varName}}
        {% endfor %}
        return parameters
    }
}

// === Parameters template ends ===
// === Parameters ends ===
