pluginInfo:
  # This is default sample specification
  # Feel free to change it
  # Call pdk showdoc pluginspec to see the list of available fields and their description
  pluginName: 'samplepoc'
  version: '1.0.5'
  description: 'Samplepoc'
  author: 'Rajan'
  supportUrl: 'http:samplepoc.com'
  category: 'Utilities'
  shell: 'ec-groovy'

# Plugin configuration description
configuration:
  # This is a shell used for checking connection
  shell: 'ec-groovy'
  # A script for checking connection will be generated
  checkConnection: 'true'
  # A set of fields will be added to process debug level in the configuration
  hasDebugLevel: true
  parameters:
  -
    name: config
    documentation: The name for the created configuration
    required: true
    type: entry
    label: Configuration Name
  -
    name: desc
    documentation: Description for the configuration
    required: false
    type: entry
    label: Description
  -
    name: endpoint
    documentation: Third-party endpoint to connect to.
    required: true
    type: entry
    label: Endpoint
  -
    name: accesstoken
    documentation: A sample credential
    required: true
    type: entry
    label: Access token

procedures:
-
  name: 'Sample Procedure'
  description: 'Sample procedure description'
  # configuration field will be generated automatically
  hasConfig: true
  parameters:
  -
    name: branchName
    documentation: Path to the application
    required: true
    type: entry
    label: Branch Name
  -
    name: ownername
    documentation: Path to the application
    required: true
    type: entry
    label: ownername   
  -
    name: reponame
    documentation: Path to the application
    required: true
    type: entry
    label: reponame
  outputParameters:
    deployed: 'JSON representation of the deployed application'
-
  name: 'OrgCreation Procedure'
  description: 'OrgCreation procedure description'
  # configuration field will be generated automatically
  hasConfig: true
  parameters:
  -
    name: orgName
    documentation: Path to the application
    required: true
    type: entry
    label: orgName
  outputParameters:
    deployed: 'JSON representation of the deployed application'

